name: 'Dependency Review'
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@2ce029c676cacb6112c47192ee072c7f783330c5
        with:
          comment-summary-in-pr: always
